<?xml version="1.0"?>
<package format="3">
  <name>psilia_runtime</name>
  <version>0.0.1</version>
  <description>Psilia spatial perception ROS nodes</description>
  <maintainer email="hello@psilia.ai">Psilia</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>rosbridge_server</depend>
  <depend>foxglove_bridge</depend>
  <depend>builtin_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
